### ISSUE TITLE
Mysterious error on collation attempt

### ISSUE THREAD

**Issue by tla** [interedition/collatex#44]
Hi - I have run into an error when trying to collate the attached JSON input, which doesn't give much idea of the problem. If I remove the first witness (Bz449) then it works, but I can't see anything obviously wrong in the Bz449 input. Any hints would be very welcome.

```
Taras-iMac:collatex tla$ collatex -t --format json milestone-455.json > /dev/null
Unexpected error
null
Taras-iMac:collatex tla$
```

[milestone-455.json.gz](https://github.com/interedition/collatex/files/1288781/milestone-455.json.gz)

**Comment by tla** [comment]
(p.s. `collatex` is a local wrapper that sets JAVA_HOME and executes the JAR file.)

**Comment by rhdekker** [comment]
Hi,

Tried this on the latest code in the master branch and I can replicate the error. It gives me a little bit more information.

java -jar collatex-tools-1.8-SNAPSHOT.jar -t --format json ~/Downloads/milestone-455.json
Unexpected error
null
java.lang.NullPointerException
	at eu.interedition.collatex.dekker.DekkerAlgorithm.collate(DekkerAlgorithm.java:187)
	at eu.interedition.collatex.tools.CollationPipe.start(CollationPipe.java:153)
	at eu.interedition.collatex.tools.CollateX.main(CollateX.java:45)

I am not yet sure what actually causes the error but at least this brings us a step further.

**Comment by rhdekker** [comment]
Hi,

I tried to collate the input data with the latest experimental version of the collation algorithm in a development branch and it returns without error. I included the output as an attachment to this method. Can you take a look at it and give feedback what you think of the quality of the alignment?

[output_tara.json.zip](https://github.com/interedition/collatex/files/1293008/output_tara.json.zip)

Best,
Ronald

**Comment by tla** [comment]
Finally she replies...! Insofar as the input isn't regularised, I think the alignment is fine. Thanks, belatedly, for looking into this!

**Comment by rhdekker** [comment]
The working version is in the master branch. The only reason I have not released this code is that this algorithm does not yet support transposition detection, which would be a feature reduction and would most likely result in complains.

Building is done using apache maven, I think the proper command is mvn package. A target directory will be created which contains the jar file.

On 15 Feb 2018, at 18:21, tla <notifications@github.com<mailto:notifications@github.com>> wrote:


A follow-up question: which development branch has the working version, and how might I build it?
